# Generated by Django 5.0.7 on 2024-09-01 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuda_Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('unidade', models.CharField(max_length=100)),
                ('carga_horaria', models.CharField(choices=[('12_horas', '12 Horas'), ('24_horas', '24 Horas')], max_length=30)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('majorado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataMajorada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
            ],
        ),
    ]
