# Generated by Django 5.0.7 on 2024-09-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0001_initial'),
        ('servidor', '0009_alter_servidor_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAjudaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_horas', models.IntegerField()),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
            ],
        ),
    ]
