# Generated by Django 5.0.7 on 2024-09-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajuda_custo', '0001_initial'),
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteajudacusto',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
