# Generated by Django 5.0.7 on 2024-10-01 18:08

from django.db import migrations
import ajuda_custo.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0001_initial'),
    ]



    operations = [

    migrations.CreateModel(
        name='Ajuda_Custo',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('matricula', models.IntegerField()),
            ('nome', models.CharField(max_length=100)),
            ('data', models.DateField()),
            ('unidade', models.CharField(max_length=100)),
            ('carga_horaria',
             models.CharField(choices=[('12 horas', '12 Horas'), ('24 horas', '24 Horas')], max_length=30)),
            ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
            ('majorado', models.BooleanField(default=False)),
            ('folha_assinada',
             models.FileField(blank=True, null=True, upload_to=ajuda_custo.models.upload_to_ajuda_custo)),
        ],
    )
        ]
