# Generated by Django 5.0.7 on 2024-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuda_custo',
            name='teste',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
