# Generated by Django 5.0.7 on 2024-10-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajuda_custo',
            name='majorado',
        ),
    ]
