# Generated by Django 5.0.7 on 2024-09-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda_custo',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
