# Generated by Django 5.0.7 on 2024-10-01 17:06

import ajuda_custo.models
from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.AddField(
            model_name='ajuda_custo',
            name='folha_assinada',
            field=models.FileField(blank=True, null=True, upload_to=ajuda_custo.models.upload_to_ajuda_custo),
        ),
    ]
