# Generated by Django 5.0.7 on 2024-09-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0002_alter_ajuda_custo_matricula'),
        ('servidor', '0003_alter_servidor_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda_custo',
            name='carga_horaria',
            field=models.CharField(choices=[('12 horas', '12 Horas'), ('24 horas', '24 Horas')], max_length=30),
        ),
        migrations.CreateModel(
            name='LimiteAjudaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_horas', models.IntegerField()),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
            ],
        ),
    ]
