# Generated by Django 5.0.7 on 2024-08-26 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0002_unidade_ajuda_custo'),
        ('seappb', '0007_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda_custo',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade'),
        ),
        migrations.RemoveField(
            model_name='ajuda_custo',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ajuda_custo',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajudacusto_registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
