# Generated by Django 5.0.7 on 2025-01-05 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0002_remove_ajuda_custo_majorado'),
        ('seappb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteajudacusto',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade'),
        ),
        migrations.CreateModel(
            name='CotaAjudaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cota_ajudacusto', models.PositiveIntegerField()),
                ('carga_horaria_total', models.PositiveIntegerField(default=0, editable=False)),
                ('carga_horaria_disponivel', models.PositiveIntegerField(default=0, editable=False)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
            ],
        ),
    ]
