# Generated by Django 5.0.7 on 2024-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0003_alter_ajuda_custo_unidade_remove_ajuda_custo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda_custo',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
