# Generated by Django 5.0.7 on 2025-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0003_limiteajudacusto_unidade_cotaajudacusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuda_custo',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
