# Generated by Django 5.0.7 on 2024-10-01 16:09

import ajuda_custo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0003_remove_ajuda_custo_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda_custo',
            name='folha_assinada',
            field=models.FileField(blank=True, default=None, upload_to=ajuda_custo.models.upload_to_ajuda_custo),
            preserve_default=False,
        ),
    ]
