# Generated by Django 5.0.7 on 2025-04-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0004_ajuda_custo_codigo_verificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Matrícula Importante',
                'verbose_name_plural': 'Matrículas Importantes',
            },
        ),
    ]
