# Generated by Django 5.0.7 on 2024-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0005_alter_ajuda_custo_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuda_custo',
            name='majorada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ajuda_custo',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
