# Generated by Django 5.0.7 on 2025-04-06 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0005_matriculaimportante'),
        ('servidor', '0007_servidor_disposicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculaimportante',
            name='nome',
        ),
        migrations.AddField(
            model_name='matriculaimportante',
            name='servidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_importantes', to='servidor.servidor'),
            preserve_default=False,
        ),
    ]
