# Generated by Django 5.0.7 on 2024-08-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda_custo', '0006_ajuda_custo_majorada_ajuda_custo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajuda_custo',
            old_name='majorada',
            new_name='majorado',
        ),
    ]
