# Generated by Django 5.0.7 on 2025-02-03 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interno', '0001_initial'),
        ('seappb', '0006_alter_unidade_reisp'),
        ('servidor', '0007_servidor_disposicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('nome', models.CharField(max_length=255)),
                ('prontuario', models.CharField(blank=True, max_length=255, null=True)),
                ('localizado', models.BooleanField(default=False)),
                ('outros', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_hospitalar', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_saida', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interno.interno')),
                ('unidade_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='copen.natureza')),
            ],
        ),
        migrations.CreateModel(
            name='Apreensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.IntegerField(default=0)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copen.natureza')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copen.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='Mp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mae', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cumprimento', models.DateField(default=django.utils.timezone.now)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interno.interno')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copen.tipomp')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('outros', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interno.interno')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copen.tipoocorrencia')),
            ],
        ),
    ]
