# Generated by Django 5.0.7 on 2025-02-12 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='status_preso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='copen.statuspreso'),
        ),
    ]
