# Generated by Django 5.0.7 on 2025-02-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copen', '0003_alter_statuspreso_options_statuspreso_ordem'),
        ('servidor', '0007_servidor_disposicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
