# Generated by Django 5.0.7 on 2025-02-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copen', '0004_alter_ocorrencia_servidor'),
        ('interno', '0002_alter_interno_cpf'),
        ('seappb', '0006_alter_unidade_reisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interno.interno'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade'),
        ),
    ]
