# Generated by Django 5.0.7 on 2025-04-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copen', '0005_alter_ocorrencia_interno_alter_ocorrencia_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natureza',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='objeto',
            options={'ordering': ['nome']},
        ),
    ]
