# Generated by Django 5.0.7 on 2024-09-15 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gesipe_adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('processos', models.IntegerField(blank=True, default=0)),
                ('memorandos_diarias', models.IntegerField(blank=True, default=0)),
                ('memorandos_documentos_capturados', models.IntegerField(blank=True, default=0)),
                ('despachos_gerencias', models.IntegerField(blank=True, default=0)),
                ('despachos_unidades', models.IntegerField(blank=True, default=0)),
                ('despachos_grupos', models.IntegerField(blank=True, default=0)),
                ('oficios_internos_unidades_prisionais', models.IntegerField(blank=True, default=0)),
                ('oficios_internos_setores_seap_pb', models.IntegerField(blank=True, default=0)),
                ('oficios_internos_circular', models.IntegerField(blank=True, default=0)),
                ('oficios_externos_seap_pb', models.IntegerField(blank=True, default=0)),
                ('oficios_externos_diversos', models.IntegerField(blank=True, default=0)),
                ('oficios_externos_judiciario', models.IntegerField(blank=True, default=0)),
                ('os_grupos', models.IntegerField(blank=True, default=0)),
                ('os_diversos', models.IntegerField(blank=True, default=0)),
                ('portarias', models.IntegerField(blank=True, default=0)),
                ('total_memorando', models.IntegerField(blank=True, default=0)),
                ('total_despacho', models.IntegerField(blank=True, default=0)),
                ('total_oficio', models.IntegerField(blank=True, default=0)),
                ('total_os', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
