# Generated by Django 5.0.7 on 2024-11-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gesipe_adm',
            old_name='memorandos_diarias',
            new_name='diarias',
        ),
        migrations.RenameField(
            model_name='gesipe_adm',
            old_name='memorandos_documentos_capturados',
            new_name='documentos_capturados',
        ),
    ]
