# Generated by Django 5.0.7 on 2024-08-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesipe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesipe_adm',
            name='total_despacho',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gesipe_adm',
            name='total_memorando',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gesipe_adm',
            name='total_oficio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gesipe_adm',
            name='total_os',
            field=models.IntegerField(default=0),
        ),
    ]
