# Generated by Django 5.0.7 on 2024-11-21 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesipe', '0002_rename_memorandos_diarias_gesipe_adm_diarias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gesipe_Sga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('agendamentos_entradas', models.IntegerField(blank=True, default=0)),
                ('comunicacoes_presos', models.IntegerField(blank=True, default=0)),
                ('comunicacoes_servidores', models.IntegerField(blank=True, default=0)),
                ('comunicacoes_setores', models.IntegerField(blank=True, default=0)),
                ('comunicacoes_judiciais_externas', models.IntegerField(blank=True, default=0)),
                ('om_grupos', models.IntegerField(blank=True, default=0)),
                ('om_unidades', models.IntegerField(blank=True, default=0)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes_sga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['data'], name='gesipe_gesi_data_83086a_idx')],
            },
        ),
    ]
