# Generated by Django 5.0.7 on 2024-08-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesipe', '0003_gesipe_adm_total_despacho_gesipe_adm_total_memorando_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesipe_adm',
            name='despachos_gerencias',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='despachos_grupos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='despachos_unidades',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='memorandos_diarias',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='memorandos_documentos_capturados',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='oficios_externos_diversos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='oficios_externos_judiciario',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='oficios_externos_seap_pb',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='oficios_internos_circular',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='oficios_internos_setores_seap_pb',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='oficios_internos_unidades_prisionais',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='os_diversos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='os_grupos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='portarias',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='processos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='total_despacho',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='total_memorando',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='total_oficio',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gesipe_adm',
            name='total_os',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
