# Generated by Django 5.0.7 on 2025-01-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
