# Generated by Django 5.0.7 on 2024-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
