# Generated by Django 5.0.7 on 2024-08-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.CharField(default='teste', max_length=100),
        ),
    ]
