# Generated by Django 5.0.7 on 2024-10-26 19:16

import seappb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0002_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=seappb.models.user_directory_path),
        ),
    ]
