# Generated by Django 5.0.7 on 2024-08-21 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0002_setor_alter_usuario_matricula_alter_usuario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.setor'),
        ),
    ]
