# Generated by Django 5.0.7 on 2025-01-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0002_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(blank=True, default=None, unique=True),
            preserve_default=False,
        ),
    ]
