# Generated by Django 5.0.6 on 2024-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0003_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
