# Generated by Django 5.0.7 on 2024-08-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0003_alter_usuario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
