# Generated by Django 5.0.7 on 2025-01-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0003_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
