# Generated by Django 5.0.7 on 2025-01-27 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cep',
            field=models.CharField(default='58000-000', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O CEP deve estar no formato 12345-678', regex='^\\d{5}-\\d{3}$')]),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(blank=True, choices=[('ÁGUA BRANCA', 'ÁGUA BRANCA'), ('AGUIAR', 'AGUIAR'), ('ALAGOA GRANDE', 'ALAGOA GRANDE'), ('ALAGOA NOVA', 'ALAGOA NOVA'), ('ALAGOINHA', 'ALAGOINHA'), ('ALCANTIL', 'ALCANTIL'), ('ALGODÃO DE JANDAÍRA', 'ALGODÃO DE JANDAÍRA'), ('ALHANDRA', 'ALHANDRA'), ('SÃO JOÃO DO RIO DO PEIXE', 'SÃO JOÃO DO RIO DO PEIXE'), ('AMPARO', 'AMPARO'), ('APARECIDA', 'APARECIDA'), ('ARAÇAGI', 'ARAÇAGI'), ('ARARA', 'ARARA'), ('ARARUNA', 'ARARUNA'), ('AREIA', 'AREIA'), ('AREIA DE BARAÚNAS', 'AREIA DE BARAÚNAS'), ('AREIAL', 'AREIAL'), ('AROEIRAS', 'AROEIRAS'), ('ASSUNÇÃO', 'ASSUNÇÃO'), ('BAÍA DA TRAIÇÃO', 'BAÍA DA TRAIÇÃO'), ('BANANEIRAS', 'BANANEIRAS'), ('BARAÚNA', 'BARAÚNA'), ('BARRA DE SANTANA', 'BARRA DE SANTANA'), ('BARRA DE SANTA ROSA', 'BARRA DE SANTA ROSA'), ('BARRA DE SÃO MIGUEL', 'BARRA DE SÃO MIGUEL'), ('BAYEUX', 'BAYEUX'), ('BELÉM', 'BELÉM'), ('BELÉM DO BREJO DO CRUZ', 'BELÉM DO BREJO DO CRUZ'), ('BERNARDINO BATISTA', 'BERNARDINO BATISTA'), ('BOA VENTURA', 'BOA VENTURA'), ('BOA VISTA', 'BOA VISTA'), ('BOM JESUS', 'BOM JESUS'), ('BOM SUCESSO', 'BOM SUCESSO'), ('BONITO DE SANTA FÉ', 'BONITO DE SANTA FÉ'), ('BOQUEIRÃO', 'BOQUEIRÃO'), ('IGARACY', 'IGARACY'), ('BORBOREMA', 'BORBOREMA'), ('BREJO DO CRUZ', 'BREJO DO CRUZ'), ('BREJO DOS SANTOS', 'BREJO DOS SANTOS'), ('CAAPORÃ', 'CAAPORÃ'), ('CABACEIRAS', 'CABACEIRAS'), ('CABEDELO', 'CABEDELO'), ('CACHOEIRA DOS ÍNDIOS', 'CACHOEIRA DOS ÍNDIOS'), ('CACIMBA DE AREIA', 'CACIMBA DE AREIA'), ('CACIMBA DE DENTRO', 'CACIMBA DE DENTRO'), ('CACIMBAS', 'CACIMBAS'), ('CAIÇARA', 'CAIÇARA'), ('CAJAZEIRAS', 'CAJAZEIRAS'), ('CAJAZEIRINHAS', 'CAJAZEIRINHAS'), ('CALDAS BRANDÃO', 'CALDAS BRANDÃO'), ('CAMALAÚ', 'CAMALAÚ'), ('CAMPINA GRANDE', 'CAMPINA GRANDE'), ('CAPIM', 'CAPIM'), ('CARAÚBAS', 'CARAÚBAS'), ('CARRAPATEIRA', 'CARRAPATEIRA'), ('CASSERENGUE', 'CASSERENGUE'), ('CATINGUEIRA', 'CATINGUEIRA'), ('CATOLÉ DO ROCHA', 'CATOLÉ DO ROCHA'), ('CATURITÉ', 'CATURITÉ'), ('CONCEIÇÃO', 'CONCEIÇÃO'), ('CONDADO', 'CONDADO'), ('CONDE', 'CONDE'), ('CONGO', 'CONGO'), ('COREMAS', 'COREMAS'), ('COXIXOLA', 'COXIXOLA'), ('CRUZ DO ESPÍRITO SANTO', 'CRUZ DO ESPÍRITO SANTO'), ('CUBATI', 'CUBATI'), ('CUITÉ', 'CUITÉ'), ('CUITEGI', 'CUITEGI'), ('CUITÉ DE MAMANGUAPE', 'CUITÉ DE MAMANGUAPE'), ('CURRAL DE CIMA', 'CURRAL DE CIMA'), ('CURRAL VELHO', 'CURRAL VELHO'), ('DAMIÃO', 'DAMIÃO'), ('DESTERRO', 'DESTERRO'), ('VISTA SERRANA', 'VISTA SERRANA'), ('DIAMANTE', 'DIAMANTE'), ('DONA INÊS', 'DONA INÊS'), ('DUAS ESTRADAS', 'DUAS ESTRADAS'), ('EMAS', 'EMAS'), ('ESPERANÇA', 'ESPERANÇA'), ('FAGUNDES', 'FAGUNDES'), ('FREI MARTINHO', 'FREI MARTINHO'), ('GADO BRAVO', 'GADO BRAVO'), ('GUARABIRA', 'GUARABIRA'), ('GURINHÉM', 'GURINHÉM'), ('GURJÃO', 'GURJÃO'), ('IBIARA', 'IBIARA'), ('IMACULADA', 'IMACULADA'), ('INGÁ', 'INGÁ'), ('ITABAIANA', 'ITABAIANA'), ('ITAPORANGA', 'ITAPORANGA'), ('ITAPOROROCA', 'ITAPOROROCA'), ('ITATUBA', 'ITATUBA'), ('JACARAÚ', 'JACARAÚ'), ('JERICÓ', 'JERICÓ'), ('JOÃO PESSOA', 'JOÃO PESSOA'), ('JUAREZ TÁVORA', 'JUAREZ TÁVORA'), ('JUAZEIRINHO', 'JUAZEIRINHO'), ('JUNCO DO SERIDÓ', 'JUNCO DO SERIDÓ'), ('JURIPIRANGA', 'JURIPIRANGA'), ('JURU', 'JURU'), ('LAGOA', 'LAGOA'), ('LAGOA DE DENTRO', 'LAGOA DE DENTRO'), ('LAGOA SECA', 'LAGOA SECA'), ('LASTRO', 'LASTRO'), ('LIVRAMENTO', 'LIVRAMENTO'), ('LOGRADOURO', 'LOGRADOURO'), ('LUCENA', 'LUCENA'), ("MÃE D'ÁGUA", "MÃE D'ÁGUA"), ('MALTA', 'MALTA'), ('MAMANGUAPE', 'MAMANGUAPE'), ('MANAÍRA', 'MANAÍRA'), ('MARCAÇÃO', 'MARCAÇÃO'), ('MARI', 'MARI'), ('MARIZÓPOLIS', 'MARIZÓPOLIS'), ('MASSARANDUBA', 'MASSARANDUBA'), ('MATARACA', 'MATARACA'), ('MATINHAS', 'MATINHAS'), ('MATO GROSSO', 'MATO GROSSO'), ('MATURÉIA', 'MATURÉIA'), ('MOGEIRO', 'MOGEIRO'), ('MONTADAS', 'MONTADAS'), ('MONTE HOREBE', 'MONTE HOREBE'), ('MONTEIRO', 'MONTEIRO'), ('MULUNGU', 'MULUNGU'), ('NATUBA', 'NATUBA'), ('NAZAREZINHO', 'NAZAREZINHO'), ('NOVA FLORESTA', 'NOVA FLORESTA'), ('NOVA OLINDA', 'NOVA OLINDA'), ('NOVA PALMEIRA', 'NOVA PALMEIRA'), ("OLHO D'ÁGUA", "OLHO D'ÁGUA"), ('OLIVEDOS', 'OLIVEDOS'), ('OURO VELHO', 'OURO VELHO'), ('PARARI', 'PARARI'), ('PASSAGEM', 'PASSAGEM'), ('PATOS', 'PATOS'), ('PAULISTA', 'PAULISTA'), ('PEDRA BRANCA', 'PEDRA BRANCA'), ('PEDRA LAVRADA', 'PEDRA LAVRADA'), ('PEDRAS DE FOGO', 'PEDRAS DE FOGO'), ('PIANCÓ', 'PIANCÓ'), ('PICUÍ', 'PICUÍ'), ('PILAR', 'PILAR'), ('PILÕES', 'PILÕES'), ('PILÕEZINHOS', 'PILÕEZINHOS'), ('PIRPIRITUBA', 'PIRPIRITUBA'), ('PITIMBU', 'PITIMBU'), ('POCINHOS', 'POCINHOS'), ('POÇO DANTAS', 'POÇO DANTAS'), ('POÇO DE JOSÉ DE MOURA', 'POÇO DE JOSÉ DE MOURA'), ('POMBAL', 'POMBAL'), ('PRATA', 'PRATA'), ('PRINCESA ISABEL', 'PRINCESA ISABEL'), ('PUXINANÃ', 'PUXINANÃ'), ('QUEIMADAS', 'QUEIMADAS'), ('QUIXABA', 'QUIXABA'), ('REMÍGIO', 'REMÍGIO'), ('PEDRO RÉGIS', 'PEDRO RÉGIS'), ('RIACHÃO', 'RIACHÃO'), ('RIACHÃO DO BACAMARTE', 'RIACHÃO DO BACAMARTE'), ('RIACHÃO DO POÇO', 'RIACHÃO DO POÇO'), ('RIACHO DE SANTO ANTÔNIO', 'RIACHO DE SANTO ANTÔNIO'), ('RIACHO DOS CAVALOS', 'RIACHO DOS CAVALOS'), ('RIO TINTO', 'RIO TINTO'), ('SALGADINHO', 'SALGADINHO'), ('SALGADO DE SÃO FÉLIX', 'SALGADO DE SÃO FÉLIX'), ('SANTA CECÍLIA', 'SANTA CECÍLIA'), ('SANTA CRUZ', 'SANTA CRUZ'), ('SANTA HELENA', 'SANTA HELENA'), ('SANTA INÊS', 'SANTA INÊS'), ('SANTA LUZIA', 'SANTA LUZIA'), ('SANTANA DE MANGUEIRA', 'SANTANA DE MANGUEIRA'), ('SANTANA DOS GARROTES', 'SANTANA DOS GARROTES'), ('JOCA CLAUDINO', 'JOCA CLAUDINO'), ('SANTA RITA', 'SANTA RITA'), ('SANTA TERESINHA', 'SANTA TERESINHA'), ('SANTO ANDRÉ', 'SANTO ANDRÉ'), ('SÃO BENTO', 'SÃO BENTO'), ('SÃO BENTINHO', 'SÃO BENTINHO'), ('SÃO DOMINGOS DO CARIRI', 'SÃO DOMINGOS DO CARIRI'), ('SÃO DOMINGOS', 'SÃO DOMINGOS'), ('SÃO FRANCISCO', 'SÃO FRANCISCO'), ('SÃO JOÃO DO CARIRI', 'SÃO JOÃO DO CARIRI'), ('SÃO JOÃO DO TIGRE', 'SÃO JOÃO DO TIGRE'), ('SÃO JOSÉ DA LAGOA TAPADA', 'SÃO JOSÉ DA LAGOA TAPADA'), ('SÃO JOSÉ DE CAIANA', 'SÃO JOSÉ DE CAIANA'), ('SÃO JOSÉ DE ESPINHARAS', 'SÃO JOSÉ DE ESPINHARAS'), ('SÃO JOSÉ DOS RAMOS', 'SÃO JOSÉ DOS RAMOS'), ('SÃO JOSÉ DE PIRANHAS', 'SÃO JOSÉ DE PIRANHAS'), ('SÃO JOSÉ DE PRINCESA', 'SÃO JOSÉ DE PRINCESA'), ('SÃO JOSÉ DO BONFIM', 'SÃO JOSÉ DO BONFIM'), ('SÃO JOSÉ DO BREJO DO CRUZ', 'SÃO JOSÉ DO BREJO DO CRUZ'), ('SÃO JOSÉ DO SABUGI', 'SÃO JOSÉ DO SABUGI'), ('SÃO JOSÉ DOS CORDEIROS', 'SÃO JOSÉ DOS CORDEIROS'), ('SÃO MAMEDE', 'SÃO MAMEDE'), ('SÃO MIGUEL DE TAIPU', 'SÃO MIGUEL DE TAIPU'), ('SÃO SEBASTIÃO DE LAGOA DE ROÇA', 'SÃO SEBASTIÃO DE LAGOA DE ROÇA'), ('SÃO SEBASTIÃO DO UMBUZEIRO', 'SÃO SEBASTIÃO DO UMBUZEIRO'), ('SAPÉ', 'SAPÉ'), ('SÃO VICENTE DO SERIDÓ', 'SÃO VICENTE DO SERIDÓ'), ('SERRA BRANCA', 'SERRA BRANCA'), ('SERRA DA RAIZ', 'SERRA DA RAIZ'), ('SERRA GRANDE', 'SERRA GRANDE'), ('SERRA REDONDA', 'SERRA REDONDA'), ('SERRARIA', 'SERRARIA'), ('SERTÃOZINHO', 'SERTÃOZINHO'), ('SOBRADO', 'SOBRADO'), ('SOLÂNEA', 'SOLÂNEA'), ('SOLEDADE', 'SOLEDADE'), ('SOSSÊGO', 'SOSSÊGO'), ('SOUSA', 'SOUSA'), ('SUMÉ', 'SUMÉ'), ('TACIMA', 'TACIMA'), ('TAPEROÁ', 'TAPEROÁ'), ('TAVARES', 'TAVARES'), ('TEIXEIRA', 'TEIXEIRA'), ('TENÓRIO', 'TENÓRIO'), ('TRIUNFO', 'TRIUNFO'), ('UIRAÚNA', 'UIRAÚNA'), ('UMBUZEIRO', 'UMBUZEIRO'), ('VÁRZEA', 'VÁRZEA'), ('VIEIRÓPOLIS', 'VIEIRÓPOLIS'), ('ZABELÊ', 'ZABELÊ')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='estado',
            field=models.CharField(default='PARAIBA', max_length=255),
        ),
        migrations.AddField(
            model_name='unidade',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='pais',
            field=models.CharField(default='BRASIL', max_length=255),
        ),
        migrations.AddField(
            model_name='unidade',
            name='reisp',
            field=models.IntegerField(blank=True, choices=[(1, 'REISP 1'), (2, 'REISP 2'), (3, 'REISP 3'), (4, 'REISP 4')], null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
