# Generated by Django 5.0.7 on 2024-08-21 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0004_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='seappb.setor'),
        ),
    ]
