# Generated by Django 5.0.7 on 2025-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0005_unidade_cep_unidade_cidade_unidade_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='reisp',
            field=models.IntegerField(blank=True, choices=[(1, '1° REISP'), (2, '2° REISP'), (3, '3° REISP'), (4, '4° REISP'), (5, '5° REISP')], null=True),
        ),
    ]
