# Generated by Django 5.0.7 on 2025-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0006_alter_unidade_reisp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cidade',
            field=models.CharField(blank=True, choices=[('João Pessoa', 'João Pessoa'), ('Campina Grande', 'Campina Grande'), ('Patos', 'Patos'), ('Santa Rita', 'Santa Rita'), ('Bayeux', 'Bayeux')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
