# Generated by Django 5.0.7 on 2025-04-24 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seappb', '0008_alter_unidade_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoSecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secao', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Permissão de Seção',
                'verbose_name_plural': 'Permissões de Seção',
                'unique_together': {('grupo', 'nome_secao')},
            },
        ),
    ]
