# Generated by Django 5.0.7 on 2024-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0008_remove_usuario_first_name_remove_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=200),
        ),
    ]
