# Generated by Django 5.0.7 on 2025-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seappb', '0009_permissaosecao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissaosecao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permissaosecao',
            name='grupos',
            field=models.ManyToManyField(related_name='permissoes_secao', to='auth.group'),
        ),
        migrations.RemoveField(
            model_name='permissaosecao',
            name='grupo',
        ),
    ]
