# Generated by Django 5.0.7 on 2025-02-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.IntegerField(unique=True)),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('unidade', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('data_extracao', models.DateField()),
            ],
        ),
    ]
