# Generated by Django 5.0.7 on 2025-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interno',
            name='cpf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
