# Generated by Django 5.0.7 on 2025-04-21 22:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_prisional', '0001_initial'),
        ('interno', '0002_alter_interno_cpf'),
        ('seappb', '0008_alter_unidade_cidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulacaoCarceraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateField(default=datetime.datetime.now)),
                ('regime_aberto', models.IntegerField(default=0)),
                ('regime_semiaberto', models.IntegerField(default=0)),
                ('regime_fechado', models.IntegerField(default=0)),
                ('regime_domiciliar', models.IntegerField(default=0)),
                ('provisorio', models.IntegerField(default=0)),
                ('sentenciado', models.IntegerField(default=0)),
                ('masculino', models.IntegerField(default=0)),
                ('feminino', models.IntegerField(default=0)),
                ('outros', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('plantao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='populacoes', to='gestao_prisional.ocorrenciaplantao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populacao_carceraria', to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ArquivoUpload',
        ),
        migrations.AddField(
            model_name='interno',
            name='codificacao_facial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='internos_fotos/'),
        ),
    ]
