# Generated by Django 5.0.7 on 2025-04-22 20:08

import interno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0003_populacaocarceraria_delete_arquivoupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=interno.models.PathAndRename('internos_fotos')),
        ),
    ]
