# Generated by Django 5.0.7 on 2025-05-25 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seappb', '0011_usuario_servidor'),
        ('servidor', '0007_servidor_disposicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TermoAcautelamentoCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Termos de Acautelamento',
                'verbose_name_plural': 'Contadores de Termos de Acautelamento',
            },
        ),
        migrations.CreateModel(
            name='TipoArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Munição',
                'verbose_name_plural': 'Tipos de Munição',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(choices=[(True, 'ATIVO'), (False, 'INATIVO')], default='ATIVO', max_length=50)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('calibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armaria.calibre')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armaria.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armaria.modelo')),
                ('tipo_arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armaria.tipoarma')),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='ArmamentoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armaria.armamento')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoteMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número do Lote')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Recebida')),
                ('data_validade', models.DateField()),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Recebimento')),
                ('observacoes', models.TextField(blank=True)),
                ('calibre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armaria.calibre')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armaria.tipomunicao')),
            ],
            options={
                'verbose_name': 'Lote de Munição',
                'verbose_name_plural': 'Lotes de Munição',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='BaixaMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.TextField(verbose_name='Motivo da Baixa')),
                ('documento_referencia', models.CharField(blank=True, max_length=50)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servidor.servidor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seappb.unidade')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armaria.lotemunicao')),
            ],
            options={
                'verbose_name': 'Baixa de Munição',
                'verbose_name_plural': 'Baixas de Munição',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Transferência'), ('E', 'Entrada')], max_length=1)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Documento de Referência')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='armaria.lotemunicao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servidor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municoes_recebidas', to='servidor.servidor', verbose_name='Servidor Destino')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_entrada', to='seappb.unidade')),
                ('unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_saida', to='seappb.unidade')),
            ],
            options={
                'verbose_name': 'Movimentação de Munição',
                'verbose_name_plural': 'Movimentações de Munição',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armaria.lotemunicao')),
            ],
            options={
                'verbose_name': 'Estoque de Munição',
                'verbose_name_plural': 'Estoques de Munição',
                'unique_together': {('lote', 'unidade')},
            },
        ),
    ]
