# Generated by Django 5.0.7 on 2024-09-01 17:02

import servidor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('cargo_comissionado', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, max_length=3)),
                ('simb_cargo_comissionado', models.CharField(blank=True, max_length=30, null=True)),
                ('local_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('lotacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('foto_servidor', models.ImageField(default='profile_pics/default.jpg', upload_to=servidor.models.PathAndRename('imagens_servidor'))),
                ('regime', models.CharField(choices=[('estatutario', 'Estatutário'), ('prestador', 'Prestador')], default='estatutario', max_length=50)),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default='ativo', max_length=50)),
            ],
        ),
    ]
