# Generated by Django 5.0.7 on 2024-09-15 18:09

import django.db.models.deletion
import servidor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('cargo_comissionado', models.CharField(blank=True, max_length=100, null=True)),
                ('simb_cargo_comissionado', models.CharField(blank=True, max_length=30, null=True)),
                ('local_trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('lotacao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('foto_servidor', models.ImageField(default='static/images/default.jpg', upload_to=servidor.models.PathAndRename('imagens_servidor'))),
                ('regime', models.CharField(choices=[('estatutario', 'Estatutário'), ('prestador', 'Prestador')], default='estatutario', max_length=50)),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default='ativo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
