# Generated by Django 5.0.7 on 2024-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('cargo_comissionado', models.CharField(max_length=100)),
                ('simb_cargo_comissionado', models.CharField(max_length=30)),
                ('local_trabalho', models.CharField(max_length=100)),
                ('regime', models.CharField(max_length=50)),
                ('lotacao', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
