# Generated by Django 5.0.7 on 2024-09-15 19:53

import servidor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='foto_servidor',
            field=models.ImageField(blank=True, null=True, upload_to=servidor.models.PathAndRename('imagens_servidor')),
        ),
    ]
