# Generated by Django 5.0.7 on 2024-08-21 18:35

import servidor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='foto_servidor',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=servidor.models.PathAndRename('imagens_servidor')),
        ),
        migrations.AddField(
            model_name='servidor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='servidor',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('Inativo', 'Inativo')], default='ativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cargo_comissionado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='lotacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='regime',
            field=models.CharField(choices=[('estatutario', 'Estatutário'), ('prestador', 'Prestador')], default='estatutario', max_length=50),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='simb_cargo_comissionado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
