# Generated by Django 5.0.7 on 2024-08-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_servidor_foto_servidor_servidor_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cargo_comissionado',
            field=models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='email',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default='ativo', max_length=50),
        ),
    ]
