# Generated by Django 5.0.7 on 2024-09-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_alter_servidor_foto_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='local_trabalho',
            field=models.CharField(max_length=100),
        ),
    ]
