# Generated by Django 5.0.7 on 2024-09-15 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_alter_servidor_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.CreateModel(
            name='ServidorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
