# Generated by Django 5.0.7 on 2024-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0003_alter_servidor_cargo_comissionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='email',
            field=models.TextField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
    ]
