# Generated by Django 5.0.7 on 2024-10-26 19:16

import django.db.models.deletion
import servidor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0003_alter_servidor_local_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=servidor.models.upload_documento)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='servidor.servidor')),
            ],
        ),
    ]
