# Generated by Django 5.0.7 on 2025-01-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seappb', '0005_unidade_cep_unidade_cidade_unidade_complemento_and_more'),
        ('servidor', '0004_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='local_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade'),
        ),
    ]
