# Generated by Django 5.0.7 on 2024-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0004_alter_servidor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
