# Generated by Django 5.0.7 on 2025-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0005_alter_servidor_local_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
