# Generated by Django 5.0.7 on 2024-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0005_alter_servidor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
