# Generated by Django 5.0.7 on 2024-09-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0006_alter_servidor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cargo_comissionado',
            field=models.CharField(max_length=100),
        ),
    ]
