# Generated by Django 5.0.7 on 2024-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0007_alter_servidor_cargo_comissionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cargo_comissionado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
