# Generated by Django 5.0.7 on 2024-09-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0008_alter_servidor_cargo_comissionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
