# Generated by Django 5.0.7 on 2025-04-21 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seappb', '0008_alter_unidade_cidade'),
        ('servidor', '0007_servidor_disposicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_edicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('chefe_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('servidores_extraordinario', models.ManyToManyField(related_name='plantoes_extraordinarios', to='servidor.servidor')),
                ('servidores_ordinario', models.ManyToManyField(related_name='plantoes_ordinarios', to='servidor.servidor')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seappb.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
